<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.16</version>
        <relativePath/>
    </parent>

    <groupId>io.github.kennethfan</groupId>
    <artifactId>mybatis-plus-es</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>mybatis-plus-es</name>
    <description>MyBatis-Plus 风格 API 操作 Elasticsearch 的适配层</description>

    <modules>
        <module>mp-es-core</module>
        <module>mp-es-sample</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <elasticsearch-java.version>8.19.23</elasticsearch-java.version>
        <mybatis-plus-annotation.version>3.5.17</mybatis-plus-annotation.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>co.elastic.clients</groupId>
                <artifactId>elasticsearch-java</artifactId>
                <version>${elasticsearch-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-annotation</artifactId>
                <version>${mybatis-plus-annotation.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.kennethfan</groupId>
                <artifactId>mp-es-core</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
